import { SCHEMA_VERSION, VERSION } from "../tools/project/src/version.js";

export function createPassingManualEvidence(): Record<string, unknown> {
  return {
    $schema: "../../schemas/manual-evidence.schema.json",
    schemaVersion: SCHEMA_VERSION,
    evidenceKind: "real-manual-test",
    recordedAt: "2026-07-06T00:00:00.000Z",
    modVersion: VERSION,
    notes: "Structured test summary for release gates.",
    windowsSmoke: {
      status: "pass",
      civ6Build: "civ6-build-id",
      ruleset: "RULESET_EXPANSION_2",
      modEnabledInAdditionalContent: true,
      releaseManifestValidated: true,
      copilotButtonVisible: true,
      localizedTextOk: true,
      syncCurrentTurnExported: true,
      selectiveSyncExported: true,
      luaLogLoaded: true,
      controlsAvailable: true,
      gameApiAvailable: true,
      playersApiAvailable: true,
      mapApiAvailable: true,
      base64SelfTest: true,
      sha256SelfTest: true,
      hasUnitsInPlot: true,
      hasPlayerResources: true,
      hasPlayerProgression: true,
      hasGovernmentPolicies: true,
      bridgeLatestJson: true,
      preflightPassed: true,
      validatePassed: true,
      summarizePassed: true,
      renderMapPassed: true,
      doctorPassed: true,
      visibleDataBoundaryOk: true,
      noGameplayMutationObserved: true,
      notes: "Copilot panel loaded and emitted a player-visible snapshot."
    },
    multiplayerFairness: {
      status: "pass",
      humanPlayers: 2,
      ruleset: "RULESET_EXPANSION_2",
      bothEnabledMod: true,
      separateSnapshotDirs: true,
      noDesyncObserved: true,
      copilotUsesLocalVisibilityNotice: true,
      playerA: {
        localPlayerVerified: true,
        ownCitiesOnly: true,
        ownUnitsOnlyExceptVisibleForeign: true,
        visibleForeignUnitsAreVisibleNow: true,
        noHiddenMap: true,
        noInvisibleForeignUnits: true,
        noUnmetPlayers: true,
        noOtherPlayerTechCivicsPolicies: true,
        preflightPassed: true,
        validatePassed: true,
        summarizePassed: true,
        renderMapVisibleOnly: true
      },
      playerB: {
        localPlayerVerified: true,
        ownCitiesOnly: true,
        ownUnitsOnlyExceptVisibleForeign: true,
        visibleForeignUnitsAreVisibleNow: true,
        noHiddenMap: true,
        noInvisibleForeignUnits: true,
        noUnmetPlayers: true,
        noOtherPlayerTechCivicsPolicies: true,
        preflightPassed: true,
        validatePassed: true,
        summarizePassed: true,
        renderMapVisibleOnly: true
      },
      notes: "Both player-visible snapshots remained scoped to each player's visible information."
    },
    macCodexCopilot: {
      status: "pass",
      skillInstalledValidated: true,
      handoffGenerated: true,
      codexPromptReadFirst: true,
      copilotHandoffRead: true,
      snapshotValidatedOnCopilotMachine: true,
      localVisibilityNoticeShown: true,
      syncBlockerHonored: true,
      noBlindAnalysisWhenSyncRequired: true,
      handoffScopeHonored: true,
      notes: "Mac Codex copilot used the Mod-first skill and stayed within the handoff workflow."
    }
  };
}
